In [1]:
# Diketahui array : [1, 7], [0, 5], [2, 4]
#                 : [0, 0], [7, 9], [3, 2]  6 digit nomor hp dari belakang

In [2]:
# perkalian matriks array

import numpy as np

A = np.array([[1, 7], [0, 5], [2, 4]])
B = np.array([[0, 0], [7, 9], [3, 2]])

kali = A * B
print(kali)

[[ 0  0]
 [ 0 45]
 [ 6  8]]


In [3]:
# pengurangan matriks array

import numpy as np

A = np.array([[1, 7], [0, 5], [2, 4]])
B = np.array([[0, 0], [7, 9], [3, 2]])

kurang = A - B
print(kurang)


[[ 1  7]
 [-7 -4]
 [-1  2]]


In [5]:
# transpose matriks array

import numpy as np

A = np.array([[1, 7], [0, 5], [2, 4]])
B = np.array([[0, 0], [7, 9], [3, 2]])

transpose_A = np.transpose(A)
print(transpose_A)

transpose_B = np.transpose(B)
print(transpose_B)

[[1 0 2]
 [7 5 4]]
[[0 7 3]
 [0 9 2]]


In [4]:
# invers matriks array

import numpy as np

A = np.array([[0, 5], [2, 4]])
B = np.array([[7, 9], [3, 2]])

inverse_A = np.linalg.inv(A)
print("\nInvers matriks A:")
print(inverse_A)

inverse_B = np.linalg.inv(B)
print("\nInvers matriks B:")
print(inverse_B)


Invers matriks A:
[[-0.4  0.5]
 [ 0.2  0. ]]

Invers matriks B:
[[-0.15384615  0.69230769]
 [ 0.23076923 -0.53846154]]


In [6]:
# determinan matriks array

import numpy as np

A = np.array([[0, 5], [2, 4]])
B = np.array([[7, 9], [3, 2]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

determinant_B = np.linalg.det(B)
print("Determinan dari matriks B:", determinant_B)

Determinan dari matriks A: -9.999999999999998
Determinan dari matriks B: -13.0
