In [1]:
# perkalian matriks array

import numpy as np

A = np.array([[0, 8], [9, 5], [1, 6]])
B = np.array([[0, 0], [7, 9], [3, 2]])

kali = A * B
print(kali)

[[ 0  0]
 [63 45]
 [ 3 12]]


In [3]:
# pengurangan matriks array

import numpy as np

A = np.array([[0, 8], [9, 5], [1, 6]])
B = np.array([[0, 0], [7, 9], [3, 2]])

kurang = A - B
print(kurang)


[[ 0  8]
 [ 2 -4]
 [-2  4]]


In [8]:
# transpose matriks array

import numpy as np

A = np.array([[0, 8], [9, 5], [1, 6]])
B = np.array([[0, 0], [7, 9], [3, 2]])

transpose_A = np.transpose(A)
print(transpose_A)

transpose_B = np.transpose(B)
print(transpose_B)

[[0 9 1]
 [8 5 6]]
[[0 7 3]
 [0 9 2]]


In [13]:
# invers matriks array

import numpy as np

A = np.array([[0, 8], [9, 5]])
B = np.array([[1, 6], [7, 9]])

inverse_A = np.linalg.inv(A)
print("\nInvers matriks A:")
print(inverse_A)

inverse_B = np.linalg.inv(B)
print("\nInvers matriks B:")
print(inverse_B)


Invers matriks A:
[[-0.06944444  0.11111111]
 [ 0.125       0.        ]]

Invers matriks B:
[[-0.27272727  0.18181818]
 [ 0.21212121 -0.03030303]]


In [7]:
# determinan matriks array

import numpy as np

A = np.array([[0, 8], [9, 5]])
B = np.array([[0, 0], [7, 9]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

determinant_B = np.linalg.det(B)
print("Determinan dari matriks B:", determinant_B)

Determinan dari matriks A: -72.0
Determinan dari matriks B: 0.0
